"use strict";
exports.__esModule = true;
var Televisor_1 = require("./Televisor");
var SmartTV_1 = require("./SmartTV");
console.log("-------------------------");
var tele = new Televisor_1.Televisor(0, 10, false);
console.log(tele);
tele.setCanal(30);
console.log(tele);
console.log("-------------------------");
var teleSmart = new SmartTV_1.SmartTV();
console.log(teleSmart);
teleSmart.setCanal(55);
console.log(teleSmart);
console.log("-------------------------");
var tele1 = new Televisor_1.Televisor(0, 10, true);
var tele2 = new Televisor_1.Televisor(38, 5, false);
console.log("-------------------------");
console.log(tele1);
console.log(tele2);
console.log("-------------------------");
