"use strict";
exports.__esModule = true;
var Libro_1 = require("./Libro");
var Revista_1 = require("./Revista");
var Bilioteca_1 = require("./Bilioteca");
var biblioteca1 = new Bilioteca_1.Biblioteca("1ero de Mayo", "Alsina 2654");
var libro1 = new Libro_1.Libro(123, "Borges", "Salamandra", "El examen", 40);
var revista1 = new Revista_1.Revista(332, "Jose Hernandez", "Nacion Argentina", "Martin Fierro", 30);
biblioteca1.insertar(libro1);
biblioteca1.insertar(revista1);
console.log(biblioteca1);
biblioteca1.buscar(332);
biblioteca1.buscarPorAutor("Borges");
