"use strict";
exports.__esModule = true;
var persona_1 = require("./persona");
var cuenta_1 = require("./cuenta");
var pepe = new persona_1.Persona("pepe", 123456);
var pepeAcount = new cuenta_1.Cuenta(pepe);
var juan = new persona_1.Persona("juan", 654321);
var juanAcount = new cuenta_1.Cuenta(juan, 15026);
pepeAcount.mostrarCuenta();
pepeAcount.ingresarMonto(10);
pepeAcount.mostrarCuenta();
pepeAcount.retirarMonto(50);
pepeAcount.mostrarCuenta();
console.log();
juanAcount.mostrarCuenta();
juanAcount.ingresarMonto(10);
juanAcount.mostrarCuenta();
juanAcount.retirarMonto(50);
juanAcount.mostrarCuenta();
