"use strict";
exports.__esModule = true;
var Cancion_1 = require("./Cancion");
var CD_1 = require("./CD");
var nuevoCD = new CD_1.CD();
var cancion1 = new Cancion_1.Cancion("A", "A");
var cancion2 = new Cancion_1.Cancion("B", "B");
var cancion3 = new Cancion_1.Cancion("C", "C");
var cancion4 = new Cancion_1.Cancion("D", "D");
var cancion5 = new Cancion_1.Cancion("E", "E");
var cancion6 = new Cancion_1.Cancion("F", "F");
var cancion7 = new Cancion_1.Cancion("G", "G");
var cancion8 = new Cancion_1.Cancion("H", "H");
var cancion9 = new Cancion_1.Cancion("I", "I");
nuevoCD.agregarCancion(cancion1);
nuevoCD.agregarCancion(cancion2);
nuevoCD.agregarCancion(cancion3);
nuevoCD.agregarCancion(cancion4);
nuevoCD.agregarCancion(cancion5);
nuevoCD.agregarCancion(cancion6);
nuevoCD.agregarCancion(cancion7);
nuevoCD.agregarCancion(cancion8);
nuevoCD.agregarCancion(cancion9);
console.log("-------------------------------");
console.log("Total de caciones del CD: ", nuevoCD.contarCaciones());
console.log("-------------------------------");
nuevoCD.eliminarNroDeCancion(2);
console.log("-------------------------------");
console.log("Total de caciones del CD: ", nuevoCD.contarCaciones());
console.log("-------------------------------");
nuevoCD.mostrarCancionNro(4);
console.log("-------------------------------");
nuevoCD.mostrarCancionNro(6);
console.log("-------------------------------");
var cancionAgregar = new Cancion_1.Cancion("Agregada", "Agregada");
nuevoCD.grabarCancion(3, cancionAgregar);
console.log("CONSULTAR POR QUE SALE EL UNDEFINED");
var intento = new Cancion_1.Cancion("Intento", "Intento");
nuevoCD.insertarCancion(3, intento);
